merge_rules:
  merge_mode:
    type: "default"

  update_latest: true

  merge_strategy:
    name: "squash"

  merge_commit:
    use_title_and_body: true

  labels:
    trigger: "merge-queue"

  preconditions:
    number_of_approvals: 0
    use_github_mergeability: true
